use utf8;
use Tcl::Tk;
my $int = new Tcl::Tk;
# my $mw = $int->mainwindow;
# my $text = $mw->Text->pack;
# $text->insert("end", "Мир создан!");

$int->Eval('
# pure-tcl code to create widgets (e.g. generated by some GUI builder)
pack [text .t]
.t insert end "Привет Мир!" 
');

$int->MainLoop;